### ISSUE TITLE
Use .env file for local environment configuration

### ISSUE THREAD

**Issue by jonathan-s** [embassynetwork/modernomad#358]
As per the discussion in #340. The changes that should happen are

- Use the library python-dotenv (preferred right now over pipenv)
- Create an `example.env` file that can be made into an `.env` file. 
- Make postgres the default standard in settings, currently it's sqlite.   
- Make changes to documentation explaining the `.env` file and how it can be used.

**Comment by bfirsh** [comment]
The environ library we use can already do this - `environ.Env.read_env()`.

Also worth noting that Docker Compose also reads from .env, so might be worth thinking about how these interact. I can think through this once we have an implementation, if you like. (It might be something weird like an envvar that tells the app _not_ to read from `.env` because Docker already has...)

**Comment by jonathan-s** [comment]
My suggestion would to have the `.env` in `.gitignore`. So it would be a completely local affair. Would the idea be to also use Docker for local development? Or where does Docker compose come in?

**Comment by jonathan-s** [comment]
Note to self: Change the default environment variable to postgres instead of sqlite.
